[2020-06-16 23:29:04,301] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: file_sensor_test_v1.predict_model 2020-06-11T04:05:00+00:00 [queued]>
[2020-06-16 23:29:04,318] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: file_sensor_test_v1.predict_model 2020-06-11T04:05:00+00:00 [queued]>
[2020-06-16 23:29:04,319] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-16 23:29:04,319] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-16 23:29:04,319] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-16 23:29:04,335] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): predict_model> on 2020-06-11T04:05:00+00:00
[2020-06-16 23:29:04,338] {standard_task_runner.py:53} INFO - Started process 58413 to run task
[2020-06-16 23:29:04,479] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: file_sensor_test_v1.predict_model 2020-06-11T04:05:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-06-16 23:29:05,484] {taskinstance.py:1145} ERROR - local variable 'model' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/owner/airflow/dags/file_sensor.py", line 50, in predict
    model = model.load_model("games.h5")
UnboundLocalError: local variable 'model' referenced before assignment
[2020-06-16 23:29:05,490] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-16 23:29:14,274] {logging_mixin.py:112} INFO - [2020-06-16 23:29:14,274] {local_task_job.py:103} INFO - Task exited with return code 1
